// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPTLZWZYIqsYscfyP4tV9p0YEATR2DtHU',
    appId: '1:668938805514:web:afe5478d3131e39a805af3',
    messagingSenderId: '668938805514',
    projectId: 'finsim-ff784',
    authDomain: 'finsim-ff784.firebaseapp.com',
    storageBucket: 'finsim-ff784.firebasestorage.app',
    measurementId: 'G-2XW5LZFP56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuyryjBrSdsrEynkKCgoOcAddpc1ICJNs',
    appId: '1:668938805514:android:ed663714da127efb805af3',
    messagingSenderId: '668938805514',
    projectId: 'finsim-ff784',
    storageBucket: 'finsim-ff784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3rshpH9d3MtjFigZvUAW4nLcW-K08YIA',
    appId: '1:668938805514:ios:3f0319bfae9f2e69805af3',
    messagingSenderId: '668938805514',
    projectId: 'finsim-ff784',
    storageBucket: 'finsim-ff784.firebasestorage.app',
    iosBundleId: 'com.example.finsim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3rshpH9d3MtjFigZvUAW4nLcW-K08YIA',
    appId: '1:668938805514:ios:3f0319bfae9f2e69805af3',
    messagingSenderId: '668938805514',
    projectId: 'finsim-ff784',
    storageBucket: 'finsim-ff784.firebasestorage.app',
    iosBundleId: 'com.example.finsim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPTLZWZYIqsYscfyP4tV9p0YEATR2DtHU',
    appId: '1:668938805514:web:905c4896f91f5080805af3',
    messagingSenderId: '668938805514',
    projectId: 'finsim-ff784',
    authDomain: 'finsim-ff784.firebaseapp.com',
    storageBucket: 'finsim-ff784.firebasestorage.app',
    measurementId: 'G-G0JCT3Y5FZ',
  );
}
